services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
  reactjs:
    image: node:22
    container_name: reactjs
    ports:
      - 3000:3000
    volumes:
      - ./smalltalk-reactjs:/src
      - node_modules:/src/node_modules
    command: sh -c "cd /src && npm install && npm run start"
  smalltalk-api:
    image: eclipse-temurin:21
    container_name: smalltalk-api
    environment:
      - REDIS_HOST=redis
    ports:
      - 8080:8080
    volumes:
      - .:/app:rw
      - smalltalk_build:/app/smalltalk-api/build
    working_dir: /app
    command: sh -c "./gradlew bootRun"
volumes:
  mongodb_data:
  redis_data:
  node_modules:
  smalltalk_build: