apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/urls: '["https://smalltalk-api-353443666726.asia-northeast3.run.app","https://smalltalk-api-ax6fykyr2a-du.a.run.app"]'
  labels:
    cloud.googleapis.com/location: asia-northeast3
    run.googleapis.com/satisfiesPzs: 'true'
  name: smalltalk-api
  namespace: '353443666726'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '100'
      labels:
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
      - image: asia-northeast3-docker.pkg.dev/smalltalk-438104/smalltalk/smalltalk-api:latest
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
      serviceAccountName: 353443666726-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
