spring:
    profiles:
        active: local
    application:
        name: spring-boot-graphql-smalltalk
    graphql:
        enabled: true
        path: /graphql
        graphiql:
            enabled: true
            path: /graphiql
        websocket:
            path: /graphql-ws
    data:
        redis:
            #host: localhost
            #port: 6379
            host: redis-11396.c340.ap-northeast-2-1.ec2.redns.redis-cloud.com
            port: 11396
            password: ${SMALLTALK_REDIS_PASSWORD}
            username: ${SMALLTALK_REDIS_USENAME}
        mongodb:
            uri: mongodb://admin:${SMALLTALK_MONGO_PASSWORD}@localhost:27017/tenwell?authSource=admin
    logging:
        level:
            root: INFO
            #org.springframework.web: DEBUG
            me.paulschwarz.springdotenv: TRACE


springdoc:
    swagger-ui:
        enabled: true
        path: /swagger-ui.html
    api-docs:
        path: /v3/api-docs
