spring:
    profiles:
        active: local
    application:
        name: graphql-samlltalk
    graphql:
        enabled: true
        path: /graphql
        graphiql:
            enabled: true
            path: /graphiql
        websocket:
            path: /graphql-ws
    data:
        redis:
            host: localhost
            port: 6379
        mongodb:
            uri: mongodb://admin:${MONGODB_SMALLTALK_PASSWORD}@localhost:27017/tenwell?authSource=admin
    logging:
        level:
            root: INFO
            org.springframework.web: DEBUG
            com.tenwell.product: INFO

springdoc:
    swagger-ui:
        enabled: true
        path: /swagger-ui.html
    api-docs:
        path: /v3/api-docs
